name: 'Get GitHub Release JSON'
author: Yorick Demichelis
description: 'Get GitHub Release Information from a Repository'
inputs:
  repo:
    description: 'GitHub repo under <owner>/<repo> format'
    required: true
    default: 'ctrlaltdev/get-releases-action'
  limit:
    description: 'How many releases to return'
    required: true
    default: '10'
  fields:
    description: 'Fields to return in the json, comma separated'
    required: true
    default: 'name,tag_name'
  include_prerelease:
    description: 'If prereleases should be included'
    required: true
    default: 'false'
  token:
    description: 'GitHub Token'
    required: true
outputs:
  releases:
    description: 'Releases data as JSON'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'yellow'
